Something like this will work for now.

diff --git a/setup-cloudformation-environment b/setup-cloudformation-environment
--- a/setup-cloudformation-environment
+++ b/setup-cloudformation-environment
@@ -1,26 +1,24 @@
 #! /bin/bash
-#
-#   - Discover the Cloudformation stack that booted the current instance via instance meta-data.
-#   -
-
 
 pkg="setup-cloudformation-environment"
 version="1.0"
-environment_file_path="/etc/cloudformation-environment"
 
-export AWS_DEFAULT_REGION="$(curl -sSL http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)"
-if [[ ! $AWS_DEFAULT_REGION ]]; then
-    echo "$pkg: failed to get region"
-    exit 1
+ENVIRONMENT_FILE_PATH="/etc/cloudformation-environment"
+
+export AWS_REGION="$(curl -sSL http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)"
+if [[ ! $AWS_REGION ]]; then
+  echo "$pkg: failed to get region"
+  exit 1
 fi
 
-ec2_instance_id="$(curl -sSL http://169.254.169.254/latest/meta-data/instance-id)"
-if [[ ! $ec2_instance_id ]]; then
-    echo "$pkg: failed to get instance id from instance metadata"
-    exit 2
+EC2_INSTANCE_ID="$(curl -sSL http://169.254.169.254/latest/meta-data/instance-id)"
+if [[ ! $EC2_INSTANCE_ID ]]; then
+  echo "$pkg: failed to get instance id from instance metadata"
+  exit 2
 fi
+
+aws ec2 describe-tags --filters "Name=resource-id,Values=${EC2_INSTANCE_ID}" --region ${AWS_REGION} \
+  | jq --raw-output '.Tags[] | map(select(.Key | startswith("aws:cloudformation:"))) | map({key: (.Key | gsub(":"; "_") | gsub("-"; "") | ascii_upcase), value: .Value}) | from_entries | keys[] as $k | "\($k)=\"\(.[$k])\""' \
+  > $ENVIRONMENT_FILE_PATH
 
 exit 0
-
-
-# .Tags | map(select(.Key | startswith("aws:cloudformation:"))) | map({key: .Key, value: .Value}) | from_entries
